In [15]:
import os, sklearn.cluster
from pyAudioAnalysis.MidTermFeatures import mid_feature_extraction as mT
from pyAudioAnalysis.audioBasicIO import read_audio_file, stereo_to_mono
from pyAudioAnalysis.audioSegmentation import labels_to_segments
#from pyAudioAnalysis.audioTrainTest import normalize_features
import numpy as np
import scipy.io.wavfile as wavfile
import IPython

# read signal and get normalized segment feature statistics:
input_file = os.path.join('E:/Files','Acoustic Data', 'Test_unsupervised.wav')
fs, x = read_audio_file(input_file) #fs采样频率，x波形数据
mt_size, mt_step, st_win = 1, 0.1, 0.05
[mt_feats, st_feats, _] = mT(x, fs, mt_size * fs, mt_step * fs,
                            round(fs * st_win), round(fs * st_win * 0.5))
print(mt_feats)
#(mt_feats_norm, MEAN, STD) = normalize_features([mt_feats.T])
mt_feats = mt_feats.T

# perform clustering
n_clusters = 20
x_clusters = [np.zeros((fs, )) for i in range(n_clusters)]
k_means = sklearn.cluster.KMeans(n_clusters=n_clusters)
k_means.fit(mt_feats)
cls = k_means.labels_

# save clusters to concatenated wav files
segs, c = labels_to_segments(cls, mt_step)  # convert flags to segment limits
for sp in range(n_clusters):                
    count_cl = 0
    for i in range(len(c)):     # for each segment in each cluster (>2 secs long)
        if c[i] == sp and segs[i, 1]-segs[i, 0] > 2:
            count_cl += 1
            # get the signal and append it to the cluster's signal (followed by some silence)
            cur_x = x[int(segs[i, 0] * fs): int(segs[i, 1] * fs)]
            x_clusters[sp] = np.append(x_clusters[sp], cur_x)
            x_clusters[sp] = np.append(x_clusters[sp], np.zeros((fs,)))
    # write cluster's signal into a WAV file
    print(f'cluster {sp}: {count_cl} segments {len(x_clusters[sp])/float(fs)} sec total dur')        
    wavfile.write(f'cluster_{sp}.wav', fs, np.int16(x_clusters[sp]))
    IPython.display.display(IPython.display.Audio(f'cluster_{sp}.wav'))

e:\Python\Lib\site-packages\pyAudioAnalysis\audioBasicIO.py:99: WavFileWarning: Chunk (non-data) not understood, skipping it.
  sampling_rate, signal = wavfile.read(input_file) # from scipy.io


[[0.10037915 0.10982585 0.11175374 ... 0.10913648 0.10669531 0.12280702]
 [0.01035765 0.0177821  0.01742768 ... 0.11363306 0.04910138 0.00491303]
 [2.71419743 2.7504587  2.87916934 ... 2.62562316 2.29798478 1.57327909]
 ...
 [0.01615781 0.01619737 0.02029912 ... 0.0243782  0.02966943 0.0128303 ]
 [0.00476633 0.00476707 0.0047499  ... 0.01120995 0.00957559 0.00633316]
 [0.02104143 0.01942409 0.01874324 ... 0.00949909 0.0114449  0.01372558]]
cluster 0: 0 segments 1.0 sec total dur


e:\Python\Lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


cluster 1: 0 segments 1.0 sec total dur


cluster 2: 0 segments 1.0 sec total dur


cluster 3: 0 segments 1.0 sec total dur


cluster 4: 0 segments 1.0 sec total dur


cluster 5: 0 segments 1.0 sec total dur


cluster 6: 0 segments 1.0 sec total dur


cluster 7: 0 segments 1.0 sec total dur


cluster 8: 0 segments 1.0 sec total dur


cluster 9: 0 segments 1.0 sec total dur


cluster 10: 0 segments 1.0 sec total dur


cluster 11: 0 segments 1.0 sec total dur


cluster 12: 0 segments 1.0 sec total dur


cluster 13: 0 segments 1.0 sec total dur


cluster 14: 0 segments 1.0 sec total dur


cluster 15: 0 segments 1.0 sec total dur


cluster 16: 0 segments 1.0 sec total dur


cluster 17: 0 segments 1.0 sec total dur


cluster 18: 0 segments 1.0 sec total dur


cluster 19: 0 segments 1.0 sec total dur
